dist: trusty
language: node_js

cache:
  bundler: true
  directories:
  - ./node_modules

addons:
  apt:
    packages:
      - jq

node_js:
- "stable"
before_script:
- npm install

script:
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - TOKEN=$(curl -X POST "https://auth.rustamzh.com/auth/realms/Vqms/protocol/openid-connect/token" -d "client_id=vqms&username="$USERNAME"&password="$PASSWORD"&grant_type=password" | jq -r .access_token)
    - curl -X DELETE "$URL/files?version=1.0&businessId=$BUSINESSID" -H "Authorization: Bearer $TOKEN"
    - cd dist
    - find * -type f | xargs -I {} -n 1 -t curl -X POST "$URL/files?version=1.0&relativePath={}&businessId=$BUSINESSID" -H "Authorization: Bearer $TOKEN" -F "file=@$PWD/{}"
  on:
    tags: true