dist: trusty
language: node_js

cache:
  bundler: true
  directories:
  - ./node_modules

addons:
  apt:
    packages:
      - jq

node_js:
- "stable"
before_script:
- npm install

script:
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    tags: true